function GlobalDefs_SleepStages()
%GlobalDefs_SleepStages 

global UNITS
UNITS.SECONDS_PER_HOUR = 3600; % Seconds

global EPOCH
EPOCH.DURATION = 30.0; % Epoch duration in seconds
EPOCH.EPOCHS_PER_MIN = round(60.0/EPOCH.DURATION); % Number of epochs in a minute.
EPOCH.MIN_PER_EPOCH = EPOCH.DURATION/60.0;
EPOCH.THRESHOLD_PERCENTAGE = 0.02;
EPOCH.MIN_EPOCH_DRURATION_FROM_IBIs = (1.0 - EPOCH.THRESHOLD_PERCENTAGE)*EPOCH.DURATION ;
EPOCH.MAX_EPOCH_DRURATION_FROM_IBIs = (1.0 + EPOCH.THRESHOLD_PERCENTAGE)*EPOCH.DURATION ;

global STAGE
STAGE.WAKE = 'W';
STAGE.WAKE_CODE = 0;
STAGE.WAKE_FINE_CODE = 0;
STAGE.WAKE_THRESH = 5*60/EPOCH.DURATION;
STAGE.WAKE_FILTER = ones(1,STAGE.WAKE_THRESH);
STAGE.NREM = 'N';
STAGE.NREM_CODE = 1;
STAGE.NREM_THRESH = 15*60/EPOCH.DURATION;
STAGE.NREM_FILTER = ones(1,STAGE.NREM_THRESH);
STAGE.REM = 'R';
STAGE.REM_CODE = 2;
STAGE.REM_FINE_CODE = 5;
STAGE.REM_THRESH = 5*60/EPOCH.DURATION;
STAGE.REM_FILTER = ones(1,STAGE.REM_THRESH);
STAGE.REM_THRESH_FIRST_PERIOD = 1;
STAGE.REM_THRESH_LAST_PERIOD = 1;
STAGE.PROCESSING_FROM_START = 1;

global HR_FIT
HR_FIT.GENERATE_RESULT_FILE = false;
HR_FIT.DISPLAY_HR_STAGES_GRAPH = true;
HR_FIT.FIT_HR = true;
HR_FIT.FIT_IBI = true;
HR_FIT.FIT_VALIDATED = true;
HR_FIT.FILTER_TIME_SERIES = false; % Keep data in [median-2*std,median+2*std] interval

global HRV
HRV.FILTER_TIME_SERIES = HR_FIT.FILTER_TIME_SERIES;

global EXPORT
EXPORT.VALIDATED_IBI_TIME_SERIES  = true;
EXPORT.EXECUTION_LOG_FILE = false;

global GRAPHICS
GRAPHICS.VALIDATED_IBI_TIME_SERIES = false;
GRAPHICS.SHOW_DATA_FIT_GRAPHICS = false;

% End of GlobalDefs_SleepStages function.