function GlobalDefs()
%GLOBALDEFS 

global FILES
FILES.EDF_TYPE = '*.edf';
FILES.REC_TYPE = '*.rec';
FILES.FILE_SEP = filesep;
FILES.CREATE_MAT_FILE = false;
FILES.MAT_TYPE = '.mat';
FILES.CREATE_IBI_TIMESERIES_CSV = true;
FILES.CREATE_CSV_FOR_EKG = false;
FILES.CSV_TYPE = '.csv';
FILES.DAT_TYPE = '.dat';
FILES.PNG_TYPE = '.png';
FILES.CREATE_LOG_FILE = true;
FILES.LOG_TYPE = '.log';
FILES.TXT_TYPE = '.txt';

global GRAPHICS
GRAPHICS.SHOW_INPUT_SIGNAL = false;
GRAPHICS.SHOW_PREPROCESING_STAGES = false;
GRAPHICS.SHOW_QRS_DETECTION = false;
GRAPHICS.SHOW_RRS_POST_PROCESSING = false;
GRAPHICS.SHOW_RR_TIMESERIES = true;
GRAPHICS.SAVE_RR_TIMESERIES_GRAPHICS = true;

% ECG waveform related flags
global ECG_WAVEFORM
ECG_WAVEFORM.REMOVE_PRE_POST_WAKE = true;
ECG_WAVEFORM.MINIMUM_DURATION = 60; % seconds

% Signal processing
global PRE_PROCESSING
PRE_PROCESSING.DATA_START_DATE_TIME = 0; % Posix time
PRE_PROCESSING.EPOCH_DURATION = 30; % Seconds
PRE_PROCESSING.NB_EPOCH_SAMPLES = 0;
PRE_PROCESSING.NB_COMPLETE_EPOCH = 0;
PRE_PROCESSING.BUTTERWORTH_ORDER = 3;
PRE_PROCESSING.BUTTERWORTH_CUTTOFF_LOW = 5; % Hertz
PRE_PROCESSING.BUTTERWORTH_CUTTOFF_HIGH = 15; % Hertz

% QRS detection
global PEAK_DETECTION
PEAK_DETECTION.REFACTORY_PERIOD = 0.200; % 200 ms in s
PEAK_DETECTION.NB_REFACTORY_SAMPLES = 0;
PEAK_DETECTION.LEARNING1_DURATION = 2.0; % s
PEAK_DETECTION.NB_LEARNING1_SAMPLES = 0;
PEAK_DETECTION.PEAK_SEARCH_DURATION = 0.150; % 150 ms in s
PEAK_DETECTION.NB_PEAK_SEARCH_SAMPLES = 0;
PEAK_DETECTION.T_WAVE_LOCATION = 0.360; % 360 ms in s
PEAK_DETECTION.NB_T_WAVE_LOCATION_SAMPLES = 0;
PEAK_DETECTION.SLOPE_SEARCH_DURATION = 0.075; % 75 ms in s
PEAK_DETECTION.NB_SLOPE_SEARCH_SAMPLES = 0;
PEAK_DETECTION.AMP_LOWER_THRESHOLD = 1.0e-6; % Normalized amplitude threshold limit

% Post-processing of estimated RR intervals
global POST_PROCESSING

POST_PROCESSING.REFACTORY_PERIOD = PEAK_DETECTION.REFACTORY_PERIOD; % 200 ms
POST_PROCESSING.T_WAVE = 0.360; % 360 ms
POST_PROCESSING.RR_MIN_VALUE = POST_PROCESSING.REFACTORY_PERIOD;
POST_PROCESSING.RR_MAX_VALUE = 3; % Seonds

POST_PROCESSING.BPM_PHYSIOLOGICAL_LOWER_LIMIT = 20;
POST_PROCESSING.IBI_PHYSIOLOGICAL_UPPER_LIMIT = ...
    60.0/POST_PROCESSING.BPM_PHYSIOLOGICAL_LOWER_LIMIT; % seconds
POST_PROCESSING.IBI_PHYSIOLOGICAL_LOWER_LIMIT = 0.2727; % 0.2 s -> 330 bpm and 0.2727 -> 220 bpm
POST_PROCESSING.BPM_PHYSIOLOGICAL_UPPER_LIMIT = ...
    60.0/POST_PROCESSING.IBI_PHYSIOLOGICAL_LOWER_LIMIT; % secons

POST_PROCESSING.CONTROLLING_COEFFICIENT = 0.5;
POST_PROCESSING.PROPORTION_LIMIT = 0.1; % Percent
POST_PROCESSING.BASIC_VARIABILITY = PEAK_DETECTION.REFACTORY_PERIOD; % Second

% EPOCH
% End of function GlobalDefs